# Generated by Django 6.0.6 on 2026-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool_result', 'Tool Result')], max_length=20),
        ),
    ]
