# Generated by Django 6.0.6 on 2026-06-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_message_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
